#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-click_help_colors
Version  : 0.9.1
Release  : 2
URL      : https://files.pythonhosted.org/packages/6c/c1/abc07420cfdc046c1005e16bc8090bc1f226d631b2bd172e5a8f5524c127/click-help-colors-0.9.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/6c/c1/abc07420cfdc046c1005e16bc8090bc1f226d631b2bd172e5a8f5524c127/click-help-colors-0.9.1.tar.gz
Summary  : Colorization of help messages in Click
Group    : Development/Tools
License  : MIT
Requires: pypi-click_help_colors-python = %{version}-%{release}
Requires: pypi-click_help_colors-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pypi(click)
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
=================
click-help-colors
=================
|build| |pypi| |downloads|

%package python
Summary: python components for the pypi-click_help_colors package.
Group: Default
Requires: pypi-click_help_colors-python3 = %{version}-%{release}

%description python
python components for the pypi-click_help_colors package.


%package python3
Summary: python3 components for the pypi-click_help_colors package.
Group: Default
Requires: python3-core
Provides: pypi(click_help_colors)
Requires: pypi(click)

%description python3
python3 components for the pypi-click_help_colors package.


%prep
%setup -q -n click-help-colors-0.9.1
cd %{_builddir}/click-help-colors-0.9.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1639056909
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
